import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { AKIM_DATASET as ds, EXAMPLE_DECISIONS, DEFAULT_CONSTRAINTS } from '../data/akim-v1';
import { DIRECTIONS } from '../contracts';
import { evaluate, evaluateBaseline, validateDecisions } from '../engine';
import { searchPlans, stableJson } from '../search';
import { evidenceGraph, readEvidence } from '../evidence';
import { OPTIMUM, TWO_DISTRICTS } from './fixtures';
const near = (actual: number | null, expected: number) => assert.ok(actual !== null && Math.abs(actual - expected) < 1e-9, `${actual} != ${expected}`);
test('V1 source arithmetic, exact immutable source and evidence', () => {
    near(evaluateBaseline(ds).score, 52.55768);
    const r = evaluate(ds, EXAMPLE_DECISIONS);
    near(r.score, 56.54307);
    assert.equal(r.cost, 95);
    assert.equal(r.criticalPairs.length, 0);
    assert.equal(r.districts.flatMap(d => d.indicators).length, 50);
    assert.deepEqual(r, evaluate(ds, [...EXAMPLE_DECISIONS].reverse()));
    assert.equal(evaluate(ds, []).score, null);
    assert.equal(evaluate(ds, EXAMPLE_DECISIONS.slice(0, 4)).score, null);
    assert.equal(evaluate(ds, OPTIMUM).score, 57.236735);
    near(evaluate(ds, TWO_DISTRICTS).score, 56.9977);
    assert.equal(createHash('sha256').update(readFileSync('data/akim-dataset.md')).digest('hex'), ds.sourceHash);
    const { canonicalHash, ...payload } = ds;
    assert.equal(createHash('sha256').update(stableJson(payload)).digest('hex'), canonicalHash);
    assert.ok(Object.isFrozen(ds.measures[0].effects));
    near(Object.values(ds.weights).reduce((a, b) => a + b), 1);
    near(ds.districts.reduce((a, b) => a + b.populationShare, 0), 1);
    assert.deepEqual(evaluateBaseline(ds).districts.map(d => d.score), [62.99, 57.06, 54.65, 56.63, 49.18]);
    assert.ok(evidenceGraph(r, r.evidence.at(-1)!.id).length > 100);
    assert.throws(() => readEvidence(r, ['unknown']));
    assert.ok(r.evidence.some(e => e.kind === 'synergy' && e.value === 2));
});
test('V1 strict thresholds, clipping, lags, invalid targets and constraints', () => {
    const r = evaluate(ds, [{ measureId: 'M11', districtId: 'almaty' }]);
    assert.equal(r.districts[1].indicators[0].after, 38.25);
    assert.ok(r.criticalPairs.some(p => p.districtId === 'almaty' && p.indicatorId === 'T1'));
    assert.ok(!evaluateBaseline(ds).criticalPairs.some(p => p.value === 40));
    const altered = structuredClone(ds);
    altered.districts[0].indicators.T1 = 99;
    assert.equal(evaluate(altered, [{ measureId: 'M1', districtId: 'yesil' }]).districts[0].indicators[0].after, 100);
    assert.equal(evaluate(ds, [{ measureId: 'M3', districtId: 'nura' }], { measureId: 'M3', costIncreasePct: 0, extraLagQuarters: 4 }).districts[4].indicators[0].after, 55);
    assert.equal(validateDecisions(ds, [{ measureId: 'M2', districtId: 'nura' }]).valid, false);
    assert.equal(validateDecisions(ds, [{ measureId: 'M1', districtId: null }]).valid, false);
    for (const pair of [[{ measureId: 'M1', districtId: 'nura' }, { measureId: 'M3', districtId: 'yesil' }], [{ measureId: 'M4', districtId: 'nura' }, { measureId: 'M7', districtId: 'nura' }], [{ measureId: 'M5', districtId: 'nura' }, { measureId: 'M13', districtId: 'nura' }]] as const)
        assert.equal(validateDecisions(ds, pair).valid, false);
    assert.equal(validateDecisions(ds, [{ measureId: 'M7', districtId: 'nura' }, { measureId: 'M8', districtId: 'nura' }, { measureId: 'M9', districtId: 'nura' }]).valid, false);
    assert.equal(evaluate(ds, TWO_DISTRICTS, { measureId: 'M3', costIncreasePct: 20, extraLagQuarters: 0 }).score, null);
});
test('V2 exhaustive certificates and V4 proven conflicts', async () => {
    const memory = process.memoryUsage().rss;
    let r = await searchPlans({ datasetVersion: ds.version, constraints: DEFAULT_CONSTRAINTS, deadlineMs: 60000 });
    assert.equal(r.status, 'complete');
    assert.equal(r.validCount, 694395);
    near(r.candidates[0].evaluation.score, 57.236735);
    assert.equal(r.certificate?.inputHash, r.inputHash);
    console.log(`full search ${Math.round(r.elapsedMs)}ms; RSS delta ${Math.round((process.memoryUsage().rss - memory) / 1048576)} MiB`);
    r = await searchPlans({ datasetVersion: ds.version, constraints: { ...DEFAULT_CONSTRAINTS, requiredDirections: [...DIRECTIONS] }, deadlineMs: 60000 });
    assert.equal(r.validCount, 68200);
    near(r.candidates[0].evaluation.score, 56.344510);
    assert.equal(r.candidates[0].evaluation.criticalPairs.length, 1);
    r = await searchPlans({ datasetVersion: ds.version, constraints: { ...DEFAULT_CONSTRAINTS, minDirectDistricts: 2 }, deadlineMs: 60000 });
    near(r.candidates[0].evaluation.score, 56.9977);
    r = await searchPlans({ datasetVersion: ds.version, constraints: { ...DEFAULT_CONSTRAINTS, requiredDirections: [...DIRECTIONS], maxCriticalPairs: 0 }, deadlineMs: 60000 });
    assert.equal(r.status, 'complete');
    assert.equal(r.feasibleCount, 0);
    assert.ok(r.issues.some(i => i.code === 'NURA_REQUIRES_TWO_SOCIAL'));
    r = await searchPlans({ datasetVersion: ds.version, constraints: { ...DEFAULT_CONSTRAINTS, locked: [{ measureId: 'M7', districtId: 'nura' }], excludedMeasureIds: ['M7'] } });
    assert.equal(r.feasibleCount, 0);
    assert.ok(r.issues.some(i => i.code === 'LOCK_EXCLUDED'));
    const controller = new AbortController();
    controller.abort();
    r = await searchPlans({ datasetVersion: ds.version, constraints: DEFAULT_CONSTRAINTS, signal: controller.signal });
    assert.equal(r.termination, 'cancelled');
    assert.equal(r.certificate, null);
    r = await searchPlans({ datasetVersion: ds.version, constraints: DEFAULT_CONSTRAINTS, deadlineMs: 0 });
    assert.equal(r.termination, 'deadline');
});
test('C2 locks, floors, objective, bounded cancellation and cache isolation', async () => {
    const locked = [{ measureId: 'M7' as const, districtId: 'nura' as const }];
    const constraints = { ...DEFAULT_CONSTRAINTS, locked, objective: 'minCost' as const, districtFloors: [{ districtId: 'nura' as const, minScore: 50 }], indicatorFloors: [{ districtId: 'nura' as const, indicatorId: 'S1' as const, minValue: 48 }] };
    const r = await searchPlans({ datasetVersion: ds.version, constraints, deadlineMs: 60000 });
    assert.equal(r.status, 'complete');
    assert.ok(r.candidates.length);
    for (const c of r.candidates) {
        assert.ok(c.decisions.some(d => d.measureId === 'M7' && d.districtId === 'nura'));
        assert.ok(c.evaluation.districts[4].score >= 50);
        assert.ok(c.evaluation.districts[4].indicators[4].after >= 48);
    }
    assert.equal(r.certificate?.bestValue, r.candidates[0].evaluation.cost);
    r.candidates[0].decisions.length = 0;
    const cached = await searchPlans({ datasetVersion: ds.version, constraints });
    assert.equal(cached.candidates[0].decisions.length, 5);
    const controller = new AbortController();
    setTimeout(() => controller.abort(), 5);
    const stopped = await searchPlans({ datasetVersion: ds.version, constraints: { ...DEFAULT_CONSTRAINTS, maxSpend: 99 }, signal: controller.signal });
    assert.equal(stopped.termination, 'cancelled');
    assert.equal(stopped.certificate, null);
    assert.ok(stopped.evaluatedCount > 0);
    assert.ok(stopped.elapsedMs < 1000);
});
