import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { eq } from 'drizzle-orm';
import { getDb } from '../src/server/db/core';
import { cityDatasets, cityOwners, cityShares, cityArtifacts } from '../src/server/db/schema';
import { AKIM_DATASET } from '../src/features/city/data/akim-v1';
import { createScenario, saveRevision, deleteScenario, getScenario } from '../src/server/city/scenarios';
import { compareSharedPlans, createShare, forkSharedScenario, getPublicSnapshot, listShares, parseShareToken, publicShareRoute, readSharedArtifact, revokeShare } from '../src/server/city/shares';
import type { Principal } from '../src/server/city/principal';

const admin = postgres(process.env.DATABASE_URL!, { max: 1, onnotice: () => {} });
const schema = `city_shares_test_${randomUUID().replaceAll('-', '')}`;
const globalDb = globalThis as unknown as { citySql?: ReturnType<typeof postgres> };
assert.equal(globalDb.citySql, undefined);
let isolated: ReturnType<typeof postgres> | undefined;
async function principal(): Promise<Principal> { const id = randomUUID(); await getDb().insert(cityOwners).values({ id, guestTokenHash: randomUUID(), expiresAt: new Date(Date.now() + 3600000) }); return { ownerIds: [id], primaryOwnerId: id, userId: null, kind: 'guest' }; }
try {
  await admin`create schema ${admin(schema)}`;
  const tables = await admin<{ tablename: string }[]>`select tablename from pg_tables where schemaname='public' and (tablename like 'city_%' or tablename in ('user','session','account','verification'))`;
  for (const { tablename } of tables) await admin`create table ${admin(`${schema}.${tablename}`)} (like ${admin(`public.${tablename}`)} including all)`;
  isolated = postgres(process.env.DATABASE_URL!, { max: 8, connection: { search_path: schema } }); globalDb.citySql = isolated;
  await getDb().insert(cityDatasets).values({ id: AKIM_DATASET.version, sourceHash: AKIM_DATASET.sourceHash, rulesVersion: AKIM_DATASET.rulesVersion, evaluatorVersion: AKIM_DATASET.evaluatorVersion, payload: AKIM_DATASET });
  const p = await principal(), other = await principal();
  const source = await createScenario(p, { source: 'proof', proofVariant: 'two-districts', clientMutationId: randomUUID(), title: 'Public decision' });
  const request = { revisionId: source.revision.id, artifactIds: [], teamName: 'Test team', clientMutationId: randomUUID() };
  const shared = await createShare(p, request), token = shared.token!;
  assert.match(token, /^[A-Za-z0-9_-]{43}$/);
  assert.equal((await createShare(p, request)).token, null);
  const [stored] = await getDb().select().from(cityShares).where(eq(cityShares.id, shared.share.id));
  assert.match(stored.tokenHash, /^[a-f0-9]{64}$/); assert.ok(!JSON.stringify(stored).includes(token));
  assert.equal((await listShares(p, source.scenario.id)).items[0].id, shared.share.id);
  await assert.rejects(listShares(other, source.scenario.id), { code: 'NOT_FOUND' });
  await assert.rejects(createShare(other, { ...request, clientMutationId: randomUUID() }), { code: 'NOT_FOUND' });
  await assert.rejects(revokeShare(other, shared.share.id), { code: 'NOT_FOUND' });
  const publicBefore = await getPublicSnapshot(token);
  assert.equal(publicBefore.teamName, 'Test team'); assert.equal(publicBefore.evaluation.score, source.evaluation.result.score);
  assert.ok(!JSON.stringify(publicBefore).includes(p.primaryOwnerId!)); assert.ok(!('intent' in publicBefore));
  const fork = await forkSharedScenario(other, token, { clientMutationId: randomUUID(), title: 'My copy' });
  assert.deepEqual(fork.revision.decisions, publicBefore.decisions); assert.equal(fork.scenario.title, 'My copy');
  assert.equal(fork.revision.sourceRevisionId, source.revision.id); assert.match(fork.revision.intent, /Shared snapshot/);
  await assert.rejects(getScenario(other, source.scenario.id), { code: 'NOT_FOUND' });
  const edited = await saveRevision(p, source.scenario.id, { expectedRevisionId: source.revision.id, decisions: source.revision.decisions, constraints: { ...source.revision.constraints, minDirectDistricts: 1 }, intent: 'Private updated user prompt', clientMutationId: randomUUID() });
  assert.deepEqual(await getPublicSnapshot(token), publicBefore);
  const otherShare = await createShare(other, { revisionId: fork.revision.id, artifactIds: [], teamName: 'Other team', clientMutationId: randomUUID() });
  assert.equal((await compareSharedPlans([token, otherShare.token!])).snapshots.length, 2);
  const origin = new URL(process.env.APP_URL || 'http://localhost:3000').origin;
  assert.equal(parseShareToken(`${origin}/kk/share/${token}`), token);
  assert.throws(() => parseShareToken(`https://attacker.invalid/ru/share/${token}`), { code: 'INVALID_REQUEST' });
  assert.throws(() => parseShareToken(`${origin}/ru/share/${token}?tracking=secret`), { code: 'INVALID_REQUEST' });
  const incompatible = { ...stored.snapshot, evaluation: { ...stored.snapshot.evaluation, rulesVersion: 'other-rules' } };
  await getDb().update(cityShares).set({ snapshot: incompatible }).where(eq(cityShares.id, otherShare.share.id));
  await assert.rejects(compareSharedPlans([token, otherShare.token!]), { code: 'INCOMPATIBLE_COMPARISON' });
  await getDb().update(cityShares).set({ snapshot: { ...stored.snapshot, stress: { assumption: { measureId: 'M3', costIncreasePct: 20, extraLagQuarters: 0 }, stressed: { ...stored.snapshot.evaluation, valid: false, score: null } }, evaluation: { ...stored.snapshot.evaluation, valid: false, score: null } } }).where(eq(cityShares.id, otherShare.share.id));
  await assert.rejects(compareSharedPlans([otherShare.token!]), { code: 'INCOMPATIBLE_COMPARISON' });
  await assert.rejects(readSharedArtifact(token, randomUUID()), { code: 'NOT_FOUND' });
  const fileId = randomUUID();
  await getDb().insert(cityArtifacts).values({ id: fileId, ownerId: p.primaryOwnerId!, scenarioId: source.scenario.id, revisionId: edited.revision.id, kind: 'json', locale: 'en', backend: 'local', key: `test-no-object/${fileId}`, mime: 'application/json', state: 'ready', cacheKey: fileId, clientMutationId: randomUUID() });
  await assert.rejects(createShare(p, { ...request, artifactIds: [fileId], clientMutationId: randomUUID() }), { code: 'NOT_FOUND' });
  await getDb().update(cityArtifacts).set({ revisionId: source.revision.id, state: 'pending' }).where(eq(cityArtifacts.id, fileId));
  await assert.rejects(createShare(p, { ...request, artifactIds: [fileId], clientMutationId: randomUUID() }), { code: 'ARTIFACT_NOT_READY' });
  await revokeShare(p, shared.share.id);
  await assert.rejects(getPublicSnapshot(token), { code: 'NOT_FOUND' });
  await assert.rejects(readSharedArtifact(token, fileId), { code: 'NOT_FOUND' });
  await assert.rejects(forkSharedScenario(other, token, { clientMutationId: randomUUID() }), { code: 'NOT_FOUND' });
  const replacement = await createShare(p, { ...request, clientMutationId: randomUUID() });
  await getDb().update(cityShares).set({ expiresAt: new Date(0) }).where(eq(cityShares.id, replacement.share.id));
  await assert.rejects(getPublicSnapshot(replacement.token!), { code: 'NOT_FOUND' });
  const ownerExpiry = await createShare(p, { ...request, clientMutationId: randomUUID() });
  await getDb().update(cityOwners).set({ expiresAt: new Date(0) }).where(eq(cityOwners.id, p.primaryOwnerId!));
  await assert.rejects(getPublicSnapshot(ownerExpiry.token!), { code: 'NOT_FOUND' });
  await getDb().update(cityOwners).set({ expiresAt: new Date(Date.now() + 3600000) }).where(eq(cityOwners.id, p.primaryOwnerId!));
  await deleteScenario(p, source.scenario.id);
  await assert.rejects(getPublicSnapshot(ownerExpiry.token!), { code: 'NOT_FOUND' });
  const response = await publicShareRoute(() => getPublicSnapshot(token));
  assert.equal(response.status, 404); assert.equal(response.headers.get('X-Robots-Tag'), 'noindex, nofollow'); assert.equal(response.headers.get('Referrer-Policy'), 'no-referrer'); assert.match(response.headers.get('Cache-Control')!, /no-store/);
  console.log('PASS shares: opaque hash-only token, owner isolation, immutable projection, compatible comparison, safe URL parsing, private fork, artifact alignment, revoke/expiry/owner expiry/deletion and response headers.');
} finally {
  if (isolated) await isolated.end({ timeout: 5 }); delete globalDb.citySql;
  assert.match(schema, /^city_shares_test_[a-f0-9]{32}$/); await admin`drop schema if exists ${admin(schema)} cascade`; await admin.end({ timeout: 5 });
}
