import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import postgres from 'postgres';
import { eq } from 'drizzle-orm';
import { getDb } from '../src/server/db/core';
import { cityArtifacts, cityDatasets, cityOwners, cityBriefs, cityBriefVersions } from '../src/server/db/schema';
import { AKIM_DATASET } from '../src/features/city/data/akim-v1';
import { evaluate } from '../src/features/city/engine';
import { createScenario, deleteScenario } from '../src/server/city/scenarios';
import { createArtifact } from '../src/server/city/exports';
import { createStress, getStress } from '../src/server/city/stress';
import { createBrief, editBrief } from '../src/server/city/briefs';
import { createSearch, processSearchJob } from '../src/server/city/searches';
import { claimJob } from '../src/server/city/jobs';
import { getArtifact, readArtifact, readArtifactForSnapshot, artifactChecksum, artifactDownloadResponse } from '../src/server/city/artifact-access';
import { cleanupArtifacts, deleteArtifact } from '../src/server/city/cleanup';
import { renderBriefHtml, csvCell } from '../src/features/city/brief/render';
import { briefSectionKinds, type BriefRecord } from '../src/features/city/brief/contracts';
import type { Principal } from '../src/server/city/principal';
import { readStoredObject, putStoredObject } from '../src/server/storage-core';
const admin = postgres(process.env.DATABASE_URL!, { max: 1, onnotice: () => { } }), schema = `city_exports_test_${randomUUID().replaceAll('-', '')}`;
const globalDb = globalThis as unknown as {
    citySql?: ReturnType<typeof postgres>;
};
assert.equal(globalDb.citySql, undefined);
const local = await mkdtemp(join(tmpdir(), 'city-exports-'));
process.env.STORAGE_BACKEND = 'local';
process.env.STORAGE_LOCAL_DIR = local;
let isolated: ReturnType<typeof postgres> | undefined;
async function principal(): Promise<Principal> { const id = randomUUID(); await getDb().insert(cityOwners).values({ id, guestTokenHash: randomUUID(), expiresAt: new Date(Date.now() + 3600000) }); return { ownerIds: [id], primaryOwnerId: id, userId: null, kind: 'guest' }; }
try {
    await admin `create schema ${admin(schema)}`;
    const tables = await admin<{
        tablename: string;
    }[]> `select tablename from pg_tables where schemaname='public' and (tablename like 'city_%' or tablename in ('user','session','account','verification'))`;
    for (const { tablename } of tables)
        await admin `create table ${admin(`${schema}.${tablename}`)} (like ${admin(`public.${tablename}`)} including all)`;
    isolated = postgres(process.env.DATABASE_URL!, { max: 8, connection: { search_path: schema } });
    globalDb.citySql = isolated;
    await getDb().insert(cityDatasets).values({ id: AKIM_DATASET.version, sourceHash: AKIM_DATASET.sourceHash, rulesVersion: AKIM_DATASET.rulesVersion, evaluatorVersion: AKIM_DATASET.evaluatorVersion, payload: AKIM_DATASET });
    const p = await principal(), other = await principal(), s = await createScenario(p, { source: 'proof', clientMutationId: randomUUID() });
    const input = { revisionId: s.revision.id, kind: 'json' as const, locale: 'ru' as const, clientMutationId: randomUUID() };
    const a = await createArtifact(p, input);
    assert.equal(a.state, 'ready');
    assert.equal((await createArtifact(p, { ...input, clientMutationId: randomUUID() })).id, a.id);
    const loaded = await readArtifact(p, a.id), data = JSON.parse(Buffer.from(loaded.bytes).toString());
    assert.equal(data.evaluation.result.score, s.evaluation.result.score);
    assert.equal(a.sha256, artifactChecksum(loaded.bytes));
    assert.equal(data.ownerId, undefined);
    assert.equal(data.revision.intent, undefined);
    await assert.rejects(readArtifact(other, a.id), { code: 'NOT_FOUND' });
    await assert.rejects(readArtifactForSnapshot(a.id, s.scenario.id, randomUUID()), { code: 'NOT_FOUND' });
    const response = artifactDownloadResponse(loaded);
    assert.equal(response.headers.get('x-content-type-options'), 'nosniff');
    assert.match(response.headers.get('content-disposition')!, /^attachment/);
    const b: BriefRecord = { id: randomUUID(), scenarioId: s.scenario.id, sourceRevisionId: s.revision.id, stressId: null, comparisonRevisionIds: [], version: 1, title: '<script>alert(1)</script>', locale: 'ru', sections: briefSectionKinds.map(id => ({ id, text: '<img src=x onerror=alert(1)> & author text', refs: [], userEdited: true, stale: false, generatedText: null })), sourceHash: 'fixture', status: 'needs_review', lastRunId: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
    await getDb().insert(cityBriefs).values({ id: b.id, ownerId: p.primaryOwnerId!, scenarioId: s.scenario.id, sourceRevisionId: s.revision.id, version: 1, content: b, clientMutationId: randomUUID() });
    await getDb().insert(cityBriefVersions).values({ id: randomUUID(), briefId: b.id, version: 1, content: b });
    const html = await createArtifact(p, { ...input, kind: 'html', briefId: b.id, briefVersion: 1 });
    const htmlText = Buffer.from((await readArtifact(p, html.id)).bytes).toString();
    assert.ok(htmlText.includes('&lt;script&gt;'));
    assert.ok(!htmlText.includes('<img'));
    assert.ok(htmlText.includes(String(s.evaluation.result.score)));
    const comparison = await createScenario(p, { source: 'proof', proofVariant: 'two-districts', clientMutationId: randomUUID() });
    const assumption = { measureId: s.revision.decisions[0].measureId, costIncreasePct: 0, extraLagQuarters: 1 };
    const stressId = randomUUID(), stressed = evaluate(AKIM_DATASET, comparison.revision.decisions, assumption), selected = evaluate(AKIM_DATASET, s.revision.decisions, assumption);
    const indicatorRef = s.evaluation.result.evidence.find(ref => ref.kind === 'indicator' && ref.indicatorId === 'T1')!;
    const stressRef = selected.evidence.find(ref => ref.kind === 'total')!;
    const readable = renderBriefHtml({ brief: { ...b, sections: b.sections.map(section => ({ ...section, refs: section.id === 'benefits' ? [{ evaluationId: s.evaluation.id, evidenceId: indicatorRef.id, compareToEvaluationId: comparison.evaluation.id }] : section.id === 'assumptions' ? [{ evaluationId: `stress:${stressId}:selected`, evidenceId: stressRef.id }] : [] })) }, source: s, comparisons: [comparison], stress: { experiment: { id: stressId, scenarioId: s.scenario.id, sourceRevisionId: comparison.revision.id, assumption, baseline: comparison.evaluation.result, stressed, repairRevisionIds: [s.revision.id], createdAt: new Date().toISOString() }, stale: false, repairs: [], selectedEvaluation: selected, selectedRevisionId: s.revision.id }, stale: false, versions: [1] }, 'en');
    assert.ok(readable.includes('Road congestion relief'));
    assert.ok(readable.includes('Cost increase, %'));
    assert.ok(readable.includes('Selected plan under assumption'));
    assert.ok(readable.includes(String(selected.score)));
    assert.ok(readable.includes(String(stressed.cost)));
    assert.ok(readable.includes(stressId));
    assert.ok(readable.includes(comparison.revision.id));
    assert.ok(readable.includes('&lt;img src=x onerror=alert(1)&gt; &amp; author text'));
    assert.ok(!readable.includes('<pre>') && !readable.includes('repairRevisionIds') && !readable.includes('&quot;inputs&quot;'));
    assert.ok(!readable.includes(' · ') && !readable.includes('—') && !readable.includes('–'));
    assert.ok(readable.length < 50000, 'Printable stress brief should not contain the evidence graph');
    assert.ok(readable.includes('<thead>') && readable.includes('break-inside:avoid'));
    assert.ok(readable.indexOf('<header><h1>') > 0);
    const next = { ...b, version: 2, title: 'Current private title', sections: b.sections.map(s => ({ ...s, text: 'Current author text', generatedText: 'PRIVATE PRIOR DRAFT' })) };
    await getDb().update(cityBriefs).set({ version: 2, content: next }).where(eq(cityBriefs.id, b.id));
    await getDb().insert(cityBriefVersions).values({ id: randomUUID(), briefId: b.id, version: 2, content: next });
    const historic = await createArtifact(p, { ...input, kind: 'html', briefId: b.id, briefVersion: 1, locale: 'en' });
    assert.ok(!Buffer.from((await readArtifact(p, historic.id)).bytes).toString().includes('Current private title'));
    const safeJson = await createArtifact(p, { ...input, kind: 'json', briefId: b.id, briefVersion: 2 });
    const safeText = Buffer.from((await readArtifact(p, safeJson.id)).bytes).toString();
    assert.ok(!safeText.includes('PRIVATE PRIOR DRAFT'));
    assert.ok(!safeText.includes('lastRunId'));
    for (const locale of ['ru', 'kk', 'en'] as const) {
        assert.match(renderBriefHtml({ brief: b, source: s, stress: null, comparisons: [], stale: false, versions: [1] }, locale), new RegExp(`lang="${locale}"`));
        const csv = await createArtifact(p, { ...input, kind: 'csv', locale });
        assert.ok(Buffer.from((await readArtifact(p, csv.id)).bytes).toString().includes(s.revision.id));
    }
    assert.equal(csvCell(' =WEBSERVICE("x")'), '"\' =WEBSERVICE(""x"")"');
    assert.equal(csvCell(-2), '"-2"');
    // A later repair is not a new source or brief version and must not poison a pending export.
    const savedStress = await createStress(p, { sourceRevisionId: s.revision.id, ...assumption, clientMutationId: randomUUID() });
    const pendingBrief = await createBrief(p, { sourceRevisionId: s.revision.id, stressId: savedStress.id, comparisonRevisionIds: [], locale: 'ru', clientMutationId: randomUUID() });
    const boundBrief = await editBrief(p, pendingBrief.brief.id, { expectedVersion: pendingBrief.brief.version, sectionEdits: pendingBrief.brief.sections.map(section => ({ id: section.id, text: 'Author rationale for the selected sensitivity experiment' })) });
    const stressInputs = (['json', 'csv'] as const).map(kind => ({ ...input, kind, briefId: boundBrief.brief.id, briefVersion: boundBrief.brief.version, clientMutationId: randomUUID() }));
    const stressBlocked = join(local, 'stress-blocked');
    await writeFile(stressBlocked, 'fixture');
    process.env.STORAGE_LOCAL_DIR = stressBlocked;
    for (const request of stressInputs)
        await assert.rejects(createArtifact(p, request), { code: 'STORAGE_UNAVAILABLE' });
    process.env.STORAGE_LOCAL_DIR = local;
    const pendingStressFiles = await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.briefId, boundBrief.brief.id));
    assert.equal(pendingStressFiles.length, 2);
    assert.ok(pendingStressFiles.every(row => row.state === 'failed'));
    const repairSearch = await createSearch(p, { scenarioId: s.scenario.id, inputRevisionId: s.revision.id, constraints: s.revision.constraints, assumptions: assumption, stressId: savedStress.id, limit: 1, clientRequestId: randomUUID() });
    const repairJob = await claimJob('exports-regression');
    assert.equal(repairJob?.id, repairSearch.id);
    await processSearchJob(repairJob!, new AbortController().signal);
    assert.ok((await getStress(p, savedStress.id)).experiment.repairRevisionIds.length > 0);
    for (const row of pendingStressFiles)
        await getDb().update(cityArtifacts).set({ retryAt: null }).where(eq(cityArtifacts.id, row.id));
    for (const request of stressInputs) {
        const retried = await createArtifact(p, request), before = pendingStressFiles.find(row => row.kind === request.kind)!;
        assert.equal(retried.id, before.id);
        assert.equal(retried.state, 'ready');
        assert.equal(retried.sha256, before.sha256);
        const content = Buffer.from((await readArtifact(p, retried.id)).bytes).toString();
        assert.ok(!content.includes('repairRevisionIds'));
        assert.ok(content.includes('selectedRevisionId'));
        if (request.kind === 'json') {
            const exported = JSON.parse(content);
            assert.equal(exported.stress.selectedRevisionId, s.revision.id);
            assert.deepEqual(exported.stress.selectedEvaluation, boundBrief.stress!.selectedEvaluation);
        }
    }
    assert.equal((await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.briefId, boundBrief.brief.id))).length, 2);
    // Old-format failures keep their exact tombstone; the new format receives a fresh identity.
    const legacyRequest = { ...stressInputs[0], locale: 'en' as const };
    process.env.STORAGE_LOCAL_DIR = stressBlocked;
    await assert.rejects(createArtifact(p, legacyRequest), { code: 'STORAGE_UNAVAILABLE' });
    process.env.STORAGE_LOCAL_DIR = local;
    const legacyRows = await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.briefId, boundBrief.brief.id));
    const legacy = legacyRows.find(row => row.locale === 'en')!;
    const legacyCache = createHash('sha256').update(JSON.stringify(['public-safe-v1', s.revision.id, boundBrief.brief.id, boundBrief.brief.version, 'en', 'json'])).digest('hex');
    await getDb().update(cityArtifacts).set({ cacheKey: legacyCache, updatedAt: new Date(Date.now() - 25 * 3600000) }).where(eq(cityArtifacts.id, legacy.id));
    const newFormat = await createArtifact(p, legacyRequest);
    assert.notEqual(newFormat.id, legacy.id);
    assert.equal(newFormat.state, 'ready');
    await cleanupArtifacts();
    assert.equal((await getArtifact(p, legacy.id)).state, 'deleting');
    await cleanupArtifacts();
    assert.equal((await getArtifact(p, legacy.id)).state, 'deleted');
    assert.equal(await readStoredObject(legacy.key), null);
    assert.equal((await getArtifact(p, newFormat.id)).state, 'ready');
    const failureSource = await createScenario(p, { source: 'proof', clientMutationId: randomUUID() });
    const failureInput = { ...input, revisionId: failureSource.revision.id };
    const blocked = join(local, 'blocked');
    await writeFile(blocked, 'fixture');
    process.env.STORAGE_LOCAL_DIR = blocked;
    await assert.rejects(createArtifact(p, failureInput), { code: 'STORAGE_UNAVAILABLE' });
    process.env.STORAGE_LOCAL_DIR = local;
    const [failed] = await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.revisionId, failureSource.revision.id));
    assert.equal(failed.state, 'failed');
    await getDb().update(cityArtifacts).set({ retryAt: null }).where(eq(cityArtifacts.id, failed.id));
    assert.equal((await createArtifact(p, failureInput)).id, failed.id);
    // Fail DB finalization after a real successful object upload, then retry the exact key.
    const interrupted = await createScenario(p, { source: 'proof', clientMutationId: randomUUID() });
    await isolated.unsafe(`CREATE FUNCTION fail_export_ready() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.state = 'ready' AND NEW.revision_id = '${interrupted.revision.id}' THEN RAISE EXCEPTION 'injected finalize failure'; END IF; RETURN NEW; END $$`);
    await isolated.unsafe('CREATE TRIGGER fail_export_ready BEFORE UPDATE ON city_artifacts FOR EACH ROW EXECUTE FUNCTION fail_export_ready()');
    await assert.rejects(createArtifact(p, { ...input, revisionId: interrupted.revision.id }), { code: 'STORAGE_UNAVAILABLE' });
    const [pending] = await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.revisionId, interrupted.revision.id));
    assert.ok(await readStoredObject(pending.key));
    assert.notEqual(pending.state, 'ready');
    await isolated.unsafe('DROP TRIGGER fail_export_ready ON city_artifacts');
    await getDb().update(cityArtifacts).set({ retryAt: null }).where(eq(cityArtifacts.id, pending.id));
    const recovered = await createArtifact(p, { ...input, revisionId: interrupted.revision.id });
    assert.equal(recovered.id, pending.id);
    assert.equal(recovered.state, 'ready');
    process.env.STORAGE_BACKEND = 'r2';
    await assert.rejects(readArtifact(p, a.id), { code: 'STORAGE_UNAVAILABLE' });
    process.env.STORAGE_BACKEND = 'local';
    const [corrupt] = await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.id, recovered.id));
    await putStoredObject(corrupt.key, Buffer.from('corrupt'), corrupt.mime);
    await assert.rejects(readArtifact(p, recovered.id), { code: 'STORAGE_UNAVAILABLE' });
    await deleteArtifact(p, a.id);
    await assert.rejects(readArtifact(p, a.id), { code: 'NOT_FOUND' });
    const regenerated = await Promise.all(Array.from({ length: 3 }, () => createArtifact(p, { ...input, clientMutationId: randomUUID() })));
    assert.equal(new Set(regenerated.map(item => item.id)).size, 1);
    assert.notEqual(regenerated[0].id, a.id);
    assert.equal(regenerated[0].state, 'ready');
    assert.deepEqual((await readArtifact(p, regenerated[0].id)).bytes, loaded.bytes);
    await assert.rejects(readArtifact(p, a.id), { code: 'NOT_FOUND' });
    const [replacement] = await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.id, regenerated[0].id));
    assert.equal(replacement.key, `owners/${p.primaryOwnerId}/scenarios/${s.scenario.id}/revisions/${s.revision.id}/exports/${replacement.id}.json`);
    await cleanupArtifacts();
    assert.equal((await getArtifact(p, a.id)).state, 'deleted');
    const [deleted] = await getDb().select().from(cityArtifacts).where(eq(cityArtifacts.id, a.id));
    assert.equal(await readStoredObject(deleted.key), null);
    assert.equal(deleted.cacheKey, `revoked:${a.id}`);
    assert.deepEqual((await readArtifact(p, regenerated[0].id)).bytes, loaded.bytes);
    await deleteArtifact(p, replacement.id);
    await cleanupArtifacts();
    assert.equal((await getArtifact(p, replacement.id)).state, 'deleted');
    const afterCleanup = await createArtifact(p, input);
    assert.equal(afterCleanup.state, 'ready');
    assert.notEqual(afterCleanup.id, replacement.id);
    await assert.rejects(readArtifact(p, replacement.id), { code: 'NOT_FOUND' });
    assert.deepEqual((await readArtifact(p, afterCleanup.id)).bytes, loaded.bytes);
    await deleteScenario(p, s.scenario.id);
    await assert.rejects(createArtifact(p, input), { code: 'NOT_FOUND' });
    await assert.rejects(readArtifact(p, afterCleanup.id), { code: 'NOT_FOUND' });
    console.log('PASS exports: real isolated local bytes/checksums, idempotency, JSON exact values, localized CSV, HTML escaping/author preservation, private access, download headers, put/finalize recovery, backend mismatch, revocation/cleanup and concurrent regeneration with a new identity. R2 not tested.');
}
finally {
    if (isolated)
        await isolated.end({ timeout: 5 });
    delete globalDb.citySql;
    assert.match(schema, /^city_exports_test_[a-f0-9]{32}$/);
    await admin `drop schema if exists ${admin(schema)} cascade`;
    await admin.end({ timeout: 5 });
    const target = resolve(local);
    assert.ok(target.startsWith(resolve(tmpdir()) + '\\') || target.startsWith(resolve(tmpdir()) + '/'));
    assert.match(target.split(/[\\/]/).at(-1)!, /^city-exports-/);
    await rm(target, { recursive: true, force: true });
}
