"use client";
import { useLocale, useTranslations } from "next-intl";
import type { PublicSnapshot } from "../../sharing-contracts";
import { DecisionChanges, EvaluationSummary } from "../workshop/Comparison";
export function SnapshotContent({ snapshot, base, children }: {
    snapshot: PublicSnapshot;
    base?: PublicSnapshot;
    children?: React.ReactNode;
}) {
    const t = useTranslations("delivery"), td = useTranslations("districts"), tm = useTranslations("measures"), locale = useLocale();
    const e = snapshot.evaluation;
    const n = (value: number) => new Intl.NumberFormat(locale, { maximumFractionDigits: 3 }).format(value);
    return <article className="cbd-snapshot"><header><span className="cbd-eyebrow">{snapshot.teamName || t("unnamedTeam")}</span><h3>{snapshot.title}</h3><p className="cbd-hint">{t("revision")}: {snapshot.revisionId} · {t("expires")}: {new Intl.DateTimeFormat(locale, { dateStyle: "medium" }).format(new Date(snapshot.expiresAt))}</p></header><p className="cbd-model-note">{t("modelLimit")}</p><EvaluationSummary result={e}/>{base && <p>{t("difference")}: Score {e.score === null || base.evaluation.score === null ? "—" : n(e.score - base.evaluation.score)} · {t("cost")} {n(e.cost - base.evaluation.cost)}</p>}<div className="cbd-matrix">{e.districts.map(d => <div key={d.districtId}><span>{td(d.districtId)}</span><strong>{n(d.score)}{base && <small> ({n(d.score - (base.evaluation.districts.find(v => v.districtId === d.districtId)?.score ?? 0))})</small>}</strong></div>)}{(["population", "weakest", "penalty"] as const).map(k => <div key={k}><span>{t(`component_${k}`)}</span><strong>{n(e.components[k])}</strong></div>)}</div><p className="cbd-hint">{t("direct")}: {e.directDistrictIds.map(d => td(d)).join(", ") || "—"}. {t("affected")}: {e.affectedDistrictIds.map(d => td(d)).join(", ") || "—"}.</p><h4>{t("decisions")}</h4><DecisionChanges source={base?.decisions ?? snapshot.decisions} target={snapshot.decisions}/>{snapshot.stress && <section className="cbd-risk"><h4>{t("stress")}</h4><p>{tm(snapshot.stress.assumption.measureId)} · +{snapshot.stress.assumption.costIncreasePct}% · +{snapshot.stress.assumption.extraLagQuarters} {t("quarters")}</p><EvaluationSummary result={snapshot.stress.stressed}/><p className="cbd-hint">{t("riskLimit")}</p></section>}{snapshot.brief && <section className="cbd-brief"><h4>{snapshot.brief.title}</h4><p className="cbd-hint">{t("briefVersion")}: {snapshot.brief.version} · {snapshot.brief.locale}</p>{snapshot.brief.sections.map(section => <section key={section.id}><h5>{t(`section_${section.id}`)}</h5>{section.userEdited && <span className="cbd-tag">{t("authored")}</span>}{section.stale && <p className="cbd-warning">{t("staleSection")}</p>}<p className="cbd-prose">{section.text}</p>{section.refs.length > 0 && <details><summary>{t("evidence")}</summary><ul className="cbd-references">{section.refs.map((ref, i) => <li key={i}>{ref.evaluationId} / {ref.evidenceId}{ref.compareToEvaluationId && <> · {t("comparedTo")} {ref.compareToEvaluationId}</>}</li>)}</ul></details>}</section>)}</section>}<details><summary>{t("sources")}</summary><dl className="cbd-source"><dt>{t("dataset")}</dt><dd>{e.datasetVersion}</dd><dt>{t("rules")}</dt><dd>{e.rulesVersion}</dd><dt>{t("evaluator")}</dt><dd>{e.evaluatorVersion}</dd><dt>{t("hash")}</dt><dd>{e.sourceHash}</dd></dl></details>{children}</article>;
}
