"use client";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui";
import { useScenario } from "../../client/scenario-context";
import { DIRECTIONS, DISTRICT_IDS, INDICATOR_IDS, type Constraints, type DistrictId, type IndicatorId } from "../../contracts";
import { AKIM_DATASET } from "../../data/akim-v1";
import { useState } from "react";
export function Priorities() {
    const c = useScenario(), t = useTranslations("workshop"), td = useTranslations("districts"), tm = useTranslations("measures"), ti = useTranslations("indicators"), tr = useTranslations("directions");
    const [floorDistrict, setFloorDistrict] = useState<DistrictId>("nura"), [floorIndicator, setFloorIndicator] = useState<IndicatorId>("S1"), [floorValue, setFloorValue] = useState(40);
    const q = c.constraints;
    const patch = (values: Partial<Constraints>) => c.setConstraints({ ...q, ...values });
    const num = (value: string, min: number, max: number) => Math.min(max, Math.max(min, Number(value) || 0));
    return <section className="cbw-priorities" aria-labelledby="cbw-priorities-title"><header><h3 id="cbw-priorities-title">{t("priorities")}</h3><p>{t("priorityHint")}</p></header>
 <div className="cbw-actions"><Button variant="secondary" onClick={() => patch({ minDirectDistricts: 2 })}>{t("shortcutDistricts")}</Button><Button variant="secondary" onClick={() => patch({ maxCriticalPairs: 0 })}>{t("shortcutCritical")}</Button><Button variant="secondary" onClick={() => patch({ requiredDirections: [...DIRECTIONS] })}>{t("shortcutDirections")}</Button></div>
 <div className="cbw-fields"><label>{t("maxSpend")}<input type="number" min="0" max="100" value={q.maxSpend} onChange={e => patch({ maxSpend: num(e.target.value, 0, 100) })}/></label><label>{t("minDirectDistricts")}<input type="number" min="0" max="5" value={q.minDirectDistricts} onChange={e => patch({ minDirectDistricts: Math.round(num(e.target.value, 0, 5)) })}/></label><label>{t("maxCriticalPairs")}<input type="number" min="0" max="50" placeholder={t("unlimited")} value={q.maxCriticalPairs ?? ""} onChange={e => patch({ maxCriticalPairs: e.target.value === "" ? undefined : Math.round(num(e.target.value, 0, 50)) })}/></label></div><p className="cbw-hint">{t("directHint")}</p>
 <details><summary>{t("expanded")}</summary><div className="cbw-expanded">
 <fieldset><legend>{t("requiredDirections")}</legend><div className="cbw-checks">{DIRECTIONS.map(d => <label key={d}><input type="checkbox" checked={q.requiredDirections?.includes(d) ?? false} onChange={e => patch({ requiredDirections: e.target.checked ? [...(q.requiredDirections ?? []), d] : (q.requiredDirections ?? []).filter(v => v !== d) })}/>{tr(d)}</label>)}</div></fieldset>
 <fieldset><legend>{t("locked")}</legend><p className="cbw-hint">{t("lockHint")}</p><div className="cbw-checks">{c.decisions.map(d => <label key={d.measureId}><input type="checkbox" checked={q.locked.some(v => v.measureId === d.measureId && v.districtId === d.districtId)} onChange={e => patch({ locked: e.target.checked ? [...q.locked.filter(v => v.measureId !== d.measureId), d] : q.locked.filter(v => v.measureId !== d.measureId) })}/>{tm(d.measureId)} · {d.districtId ? td(d.districtId) : t("city")}</label>)}</div>{q.locked.filter(d => !c.decisions.some(v => v.measureId === d.measureId && v.districtId === d.districtId)).map(d => <Button key={d.measureId} variant="quiet" onClick={() => patch({ locked: q.locked.filter(v => v.measureId !== d.measureId) })}>{t("remove")} {tm(d.measureId)} · {d.districtId ? td(d.districtId) : t("city")}</Button>)}</fieldset>
 <fieldset><legend>{t("excludedMeasureIds")}</legend><div className="cbw-checks">{AKIM_DATASET.measures.map(m => <label key={m.id}><input type="checkbox" checked={q.excludedMeasureIds.includes(m.id)} onChange={e => patch({ excludedMeasureIds: e.target.checked ? [...q.excludedMeasureIds, m.id] : q.excludedMeasureIds.filter(id => id !== m.id) })}/>{tm(m.id)}</label>)}</div></fieldset>
 <div className="cbw-fields"><label>{t("objective")}<select value={q.objective} onChange={e => patch({ objective: e.target.value as Constraints["objective"], priorityDistrictId: q.priorityDistrictId ?? "nura" })}>{["maxScore", "minCost", "protectDistrict"].map(v => <option key={v} value={v}>{t(v)}</option>)}</select></label>{q.objective === "protectDistrict" && <label>{t("priorityDistrict")}<select value={q.priorityDistrictId ?? "nura"} onChange={e => patch({ priorityDistrictId: e.target.value as DistrictId })}>{DISTRICT_IDS.map(d => <option key={d} value={d}>{td(d)}</option>)}</select></label>}</div>
 <fieldset><legend>{t("districtFloors")}</legend><div className="cbw-fields">{DISTRICT_IDS.map(d => <label key={d}>{td(d)}<input aria-label={`${t("districtFloors")} · ${td(d)}`} type="number" min="0" max="100" placeholder={t("unlimited")} value={q.districtFloors?.find(f => f.districtId === d)?.minScore ?? ""} onChange={e => patch({ districtFloors: [...(q.districtFloors ?? []).filter(f => f.districtId !== d), ...(e.target.value === "" ? [] : [{ districtId: d, minScore: num(e.target.value, 0, 100) }])] })}/></label>)}</div></fieldset>
 <fieldset><legend>{t("indicatorFloors")}</legend><div className="cbw-fields"><label>{t("district")}<select value={floorDistrict} onChange={e => setFloorDistrict(e.target.value as DistrictId)}>{DISTRICT_IDS.map(d => <option key={d} value={d}>{td(d)}</option>)}</select></label><label>{t("indicator")}<select value={floorIndicator} onChange={e => setFloorIndicator(e.target.value as IndicatorId)}>{INDICATOR_IDS.map(i => <option key={i} value={i}>{ti(i)}</option>)}</select></label><label>{t("minimum")}<input type="number" min="0" max="100" value={floorValue} onChange={e => setFloorValue(num(e.target.value, 0, 100))}/></label></div><Button variant="secondary" onClick={() => patch({ indicatorFloors: [...(q.indicatorFloors ?? []).filter(f => f.districtId !== floorDistrict || f.indicatorId !== floorIndicator), { districtId: floorDistrict, indicatorId: floorIndicator, minValue: floorValue }] })}>{t("addFloor")}</Button><div className="cbw-chips">{q.indicatorFloors?.map(f => <Button variant="quiet" key={`${f.districtId}:${f.indicatorId}`} onClick={() => patch({ indicatorFloors: q.indicatorFloors?.filter(v => v !== f) })}>{td(f.districtId)} · {ti(f.indicatorId)} ≥ {f.minValue} · {t("remove")}</Button>)}</div></fieldset>
 </div></details></section>;
}
