"use client";
import { useTranslations } from "next-intl";
import { useState } from "react";
import { Button } from "@/components/ui";
import { useScenario } from "../../client/scenario-context";
import { AKIM_DATASET } from "../../data/akim-v1";
import { DIRECTIONS, DISTRICT_IDS, INDICATOR_IDS, type Constraints, type DistrictId, type IndicatorId } from "../../contracts";
export function Priorities() {
    const c = useScenario(), t = useTranslations("workshop"), td = useTranslations("districts"), tm = useTranslations("measures"), ti = useTranslations("indicators"), tr = useTranslations("directions");
    const [district, setDistrict] = useState<DistrictId>("nura"), [indicator, setIndicator] = useState<IndicatorId>("S1"), [minimum, setMinimum] = useState(40);
    const q = c.constraints, patch = (v: Partial<Constraints>) => c.setConstraints({ ...q, ...v }), num = (s: string, max: number) => Math.min(max, Math.max(0, Number(s) || 0));
    const chips: {
        key: string;
        label: string;
        remove: () => void;
    }[] = [...q.locked.map(d => ({ key: `lock-${d.measureId}`, label: `${t("keepMeasure", { name: tm(d.measureId) })} · ${d.districtId ? td(d.districtId) : t("city")}`, remove: () => patch({ locked: q.locked.filter(v => v.measureId !== d.measureId) }) })), ...(q.requiredDirections ?? []).map(d => ({ key: d, label: tr(d), remove: () => patch({ requiredDirections: q.requiredDirections?.filter(v => v !== d) }) })), ...q.excludedMeasureIds.map(id => ({ key: id, label: t("withoutMeasure", { name: tm(id) }), remove: () => patch({ excludedMeasureIds: q.excludedMeasureIds.filter(v => v !== id) }) })), ...(q.districtFloors ?? []).map(f => ({ key: f.districtId, label: `${td(f.districtId)} ≥ ${f.minScore}`, remove: () => patch({ districtFloors: q.districtFloors?.filter(v => v !== f) }) })), ...(q.indicatorFloors ?? []).map(f => ({ key: `${f.districtId}-${f.indicatorId}`, label: `${td(f.districtId)} · ${ti(f.indicatorId)} ≥ ${f.minValue}`, remove: () => patch({ indicatorFloors: q.indicatorFloors?.filter(v => v !== f) }) }))];
    return <section className="cbw-priorities"><header><h3>{t("goalPrompt")}</h3></header><div className="cbw-actions"><Button variant="secondary" aria-pressed={q.minDirectDistricts === 2} onClick={() => patch({ minDirectDistricts: 2 })}>{t("shortcutDistricts")}</Button><Button variant="secondary" aria-pressed={q.maxCriticalPairs === 0} onClick={() => patch({ maxCriticalPairs: 0 })}>{t("shortcutCritical")}</Button><Button variant="secondary" aria-pressed={DIRECTIONS.every(d => q.requiredDirections?.includes(d))} onClick={() => patch({ requiredDirections: [...DIRECTIONS] })}>{t("shortcutDirections")}</Button></div>
 <div className="cbw-fields"><label>{t("maxSpend")}<input type="number" min={0} max={100} value={q.maxSpend} onChange={e => patch({ maxSpend: num(e.target.value, 100) })}/></label><label>{t("minDirectDistricts")}<input type="number" min={0} max={5} value={q.minDirectDistricts} onChange={e => patch({ minDirectDistricts: Math.round(num(e.target.value, 5)) })}/></label><label>{t("maxCriticalPairs")}<input type="number" min={0} max={50} placeholder={t("unlimited")} value={q.maxCriticalPairs ?? ""} onChange={e => patch({ maxCriticalPairs: e.target.value === "" ? undefined : Math.round(num(e.target.value, 50)) })}/></label></div><p className="cbw-hint">{t("directShort")}</p>
 <ul className="cbw-priority-chips" aria-label={t("activeConditions")}>{chips.map(chip => <li key={chip.key}><button type="button" aria-label={`${t("remove")}: ${chip.label}`} onClick={chip.remove}>{chip.label}<span aria-hidden="true">×</span></button></li>)}{q.objective !== "maxScore" && <li><span className="cbw-objective-chip">{t(q.objective)}{q.objective === "protectDistrict" && q.priorityDistrictId ? ` · ${td(q.priorityDistrictId)}` : ""}</span></li>}</ul>
 <details className="cbw-all-conditions"><summary>{t("expanded")}</summary><div className="cbw-expanded">
 <fieldset><legend>{t("requiredDirections")}</legend><div className="cbw-checks">{DIRECTIONS.map(d => <label key={d}><input type="checkbox" checked={q.requiredDirections?.includes(d) ?? false} onChange={e => patch({ requiredDirections: e.target.checked ? [...(q.requiredDirections ?? []), d] : q.requiredDirections?.filter(v => v !== d) })}/>{tr(d)}</label>)}</div></fieldset>
 <fieldset><legend>{t("locked")}</legend><p className="cbw-hint">{t("lockHint")}</p><div className="cbw-checks">{c.decisions.map(d => <label key={d.measureId}><input type="checkbox" checked={q.locked.some(v => v.measureId === d.measureId && v.districtId === d.districtId)} onChange={e => patch({ locked: e.target.checked ? [...q.locked.filter(v => v.measureId !== d.measureId), d] : q.locked.filter(v => v.measureId !== d.measureId) })}/>{tm(d.measureId)} · {d.districtId ? td(d.districtId) : t("city")}</label>)}</div></fieldset>
 <fieldset><legend>{t("excludedMeasureIds")}</legend><div className="cbw-checks">{AKIM_DATASET.measures.map(m => <label key={m.id}><input type="checkbox" checked={q.excludedMeasureIds.includes(m.id)} onChange={e => patch({ excludedMeasureIds: e.target.checked ? [...q.excludedMeasureIds, m.id] : q.excludedMeasureIds.filter(id => id !== m.id) })}/>{tm(m.id)}</label>)}</div></fieldset>
 <div className="cbw-fields"><label>{t("objective")}<select value={q.objective} onChange={e => patch({ objective: e.target.value as Constraints["objective"], priorityDistrictId: q.priorityDistrictId ?? "nura" })}>{["maxScore", "minCost", "protectDistrict"].map(v => <option key={v} value={v}>{t(v)}</option>)}</select></label>{q.objective === "protectDistrict" && <label>{t("priorityDistrict")}<select value={q.priorityDistrictId ?? "nura"} onChange={e => patch({ priorityDistrictId: e.target.value as DistrictId })}>{DISTRICT_IDS.map(d => <option key={d} value={d}>{td(d)}</option>)}</select></label>}</div>
 <fieldset><legend>{t("districtFloors")}</legend><div className="cbw-fields">{DISTRICT_IDS.map(d => <label key={d}>{td(d)}<input type="number" min={0} max={100} placeholder={t("unlimited")} value={q.districtFloors?.find(f => f.districtId === d)?.minScore ?? ""} onChange={e => patch({ districtFloors: [...(q.districtFloors ?? []).filter(f => f.districtId !== d), ...(e.target.value === "" ? [] : [{ districtId: d, minScore: num(e.target.value, 100) }])] })}/></label>)}</div></fieldset>
 <fieldset><legend>{t("indicatorFloors")}</legend><div className="cbw-fields"><label>{t("district")}<select value={district} onChange={e => setDistrict(e.target.value as DistrictId)}>{DISTRICT_IDS.map(d => <option key={d} value={d}>{td(d)}</option>)}</select></label><label>{t("indicator")}<select value={indicator} onChange={e => setIndicator(e.target.value as IndicatorId)}>{INDICATOR_IDS.map(i => <option key={i} value={i}>{ti(i)}</option>)}</select></label><label>{t("minimum")}<input type="number" min={0} max={100} value={minimum} onChange={e => setMinimum(num(e.target.value, 100))}/></label></div><Button variant="secondary" onClick={() => patch({ indicatorFloors: [...(q.indicatorFloors ?? []).filter(f => f.districtId !== district || f.indicatorId !== indicator), { districtId: district, indicatorId: indicator, minValue: minimum }] })}>{t("addFloor")}</Button></fieldset>
 </div></details></section>;
}
